spring:
  application:
    name: GridPulse

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
    database-platform: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    properties:
      hibernate:
        dialect: ${DB_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    url: ${DB_URL}
    user: ${DB_USER}
    password: ${DB_PASS}

  security:
    user:
      name: ${SPRING_SECURITY_USER_NAME}
      password: ${SPRING_SECURITY_USER_PASSWORD}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: ${JWT_EXPIRATION_TIME:86400000}
      refresh-token:
        expiration: ${REFRESH_EXPIRATION_TIME:604800000}