name: GridPulse Backend CI

on:
  push:
    branches: [ "master", "development" ]
    paths:
      - "backend/**"
      - ".github/workflows/ci-backend.yml"
  pull_request:
    branches: [ "master", "development" ]
    paths:
      - "backend/**"
      - ".github/workflows/ci-backend.yml"


jobs:
  maven-build-jar:
    name: Backend Build & Test with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v6

      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Step 3 - Build and run tests with Maven
        run: mvn -B clean verify --file backend/pom.xml

      - name: Step 4 - Upload test results (JUnit)
        if: always() # Ensure this step runs even if previous steps fail
        uses: actions/upload-artifact@v5
        with:
          name: junit-results
          path: backend/target/surefire-reports/*.xml

      - name: Step 5 - List the current directory
        run: ls -a

      - name: Step 6 - List the target folder
        run: |
          cd backend/target
          ls -a

      - name: Step 7 - List build artifacts
        run: |
          echo "Target folder content:"
          ls -la backend/target

  sonarqube-scan:
    name: SonarQube Analysis
    runs-on: ubuntu-latest
    needs: maven-build-jar

    steps:
      - name: Step 1 - Checkout
        uses: actions/checkout@v6

      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Step 3 - Build backend (required for Sonar)
        working-directory: backend
        run: mvn clean compile

      - name: Step 4 - SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v7.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: backend
          args: >
            -Dsonar.projectKey=Ammari-Youssef_GridPulse
            -Dsonar.organization=ammari-youssef
            -Dsonar.sources=src/main/java
            -Dsonar.tests=src/test/java
            -Dsonar.java.binaries=target/classes
