name: GridPulse CI/CD Pipeline

on:
  push:
    branches: [ "master", "development", "ci/ci-docker" ]
  pull_request:
    branches: [ "master", "development" ]

jobs:
  # Job 1: Backend maven build & tests
  maven-build-jar:

    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout code
        uses: actions/checkout@v5

      - name: Step 2 - Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Step 3 - Build and run tests with Maven
        run: mvn -B clean verify --file pom.xml

      - name: Step 4 - Upload test results (JUnit)
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: junit-results
          path: target/surefire-reports/*.xml

      - name: Step 5 - List the current directory
        run: ls -a

      - name: Step 6 - List the target folder
        run: |
          cd target
          ls -a

      - name: Step 7 - List build artifacts
        run: |
          echo "Target folder content:"
          ls -la target

  # Job 2: Docker image build & push
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 - Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Step 2 - Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Step 3 - Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Step 4 - Build and push
        uses: docker/build-push-action@v6
        with:
          context: .                # path to Dockerfile
          file: /Dockerfile       # Dockerfile location
          push: true
          tags: ammysf/gridpulse-cloud-backend:v1.0.0
